// 캐릭터 소개 데이터
// 여기 내용만 바꾸면 앱에 바로 반영됩니다.
// image: 캐릭터 프로필 사진 경로. 아직 없으면 null로 두면
// 색상 배경 + 이모지로 자동 대체됩니다.
const CHARACTERS = [
  {
    id: 1,
    name: "김채윤",
    tagline: "다이닝팀",
    image: "character-1.png",
    color: "#7C6CF3",
    emoji: "🌙",
    age: "중간",
    role: "팀장",
    features: [
      "고생이 많습니다.",
      "정백어가의 어머니.",
      "우정가옥의 어머니.",
    ],
    description: "독수리오형제 팀장입니다. 팀 이름이 이것으로 확정된 것은 아니지만, 그렇게 적어놨습니다. 팀장님 화이팅.",
  },
  {
    id: 2,
    name: "정민정",
    tagline: "아울렛/몰F&B팀",
    image: "character-2.png",
    color: "#F35E5E",
    emoji: "🔥",
    age: "연장자",
    role: "바이어",
    features: [
      "인플루언서 입니다.",
      "스레파 홍보 해준다고 했는데, 결국 안해줬습니다.",
      "섭섭.",
    ],
    description: "사다리타기로 캐릭터 정했는데, 혼자 좋은 캐릭터 걸렸습니다.(팀장님은 팀장님이니까 제외)",
  },
  {
    id: 3,
    name: "김윤경",
    tagline: "다이닝팀",
    image: "character-3.png",
    color: "#4FB6E8",
    emoji: "❄️",
    age: "중간",
    role: "바이어",
    features: [
      "한번 만들어 봤습니다.",
      "MD를 잘 못하고 있어서 우울합니다.",
      "그래도 우리네 인생 화이팅.",
    ],
    description: "그냥 살고 있습니다.",
  },
  {
    id: 4,
    name: "김선태",
    tagline: "아울렛/몰F&B팀",
    image: "character-4.png",
    color: "#F2B84B",
    emoji: "🌻",
    age: "막내즈",
    role: "바이어",
    features: [
      "선테토.",
      "굳세고 멋진 청년 같습니다.",
      "노원에서 살아 남았습니다.",
    ],
    description: "굳세고 멋진 청년 화이팅.",
  },
  {
    id: 5,
    name: "홍지우",
    tagline: "델리&베이커리팀",
    image: "character-5.png",
    color: "#5FBF8F",
    emoji: "🛡️",
    age: "막내즈",
    role: "바이어",
    features: [
      "부문 내 막내입니다.",
      "고생이 많습니다.",
      "노원 리뉴얼 화이팅.",
    ],
    description: "미감이 뛰어난 것 같습니다. 많은 도움 요청드립니다. 화이팅.",
  },
];
